### ISSUE TITLE
custom key binding overrides the multiple-cursor default one

### ISSUE THREAD

**Issue by littlestone** [larstvei/dot-emacs#2]
Good afternoon Lars,

Another question if you don't mind. :)

I would actually like to preserve the default multiple-cursor keybindings for the following Tips and Tricks explained at https://github.com/magnars/multiple-cursors.el:

"Sometimes you end up with cursors outside of your view. You can scroll the screen to center on each cursor with C-v and M-v or you can press C-' to hide all lines without a cursor, press C-' again to unhide."

I feel like this would be a pretty useful feature and I have noticed that the KEY "C-'" has been overridden in your custom-bindings-map with er/expand-region, how can I manage to restore the default key-bindings for multiple-cursor in my private.el file? or maybe there is another way to do it?

Thanks to advise! 

Best regards,
Junjie Tang

**Comment by larstvei** [comment]
The simplest solution is probably for you to fork the repo and just make any change you want!

This does however sound like a nice feature, so I'll change the expand-region bindings!

- Lars

**Comment by littlestone** [comment]
Super! Just a suggestion, "C-=" would be a good candidate since "C->" is also the default recommended key binding used for multiple-cursor. :)

Regards,
Junjie

**Comment by littlestone** [comment]
Lars, I really like your dot-emacs configurations, keep up the good work! :+1: 

Regards，
Junjie
