### ISSUE TITLE
multiple smaller config files

### ISSUE THREAD

**Issue by smalltimer** [larstvei/dot-emacs#4]
Hi, 

I'm trying to create my own config and am trying to learn from other people's configs. I was wondering if it is possible to set up multiple smaller config files ('.org') and then somehow collate them into the real 'init.el'. So far, I haven't seen any configs which do this, which is weird, as it can allow you to really modularise the packages. For instance, if I use, say, mu4e. You can have all the config in a .org file, and then, when you want to run sessions without the mu4e config, you simply comment out the import of the relevant config org file. 

Any tips in this regard, or perhaps blogs/configs that I should look at? 

Also, sorry for posing it as an issue - it is obviously not. I couldn't find any other way of asking you! 

Cheers

**Comment by larstvei** [comment]
Hi! 

I'm sorry, I am not following issues on this repos, so I never noticed it. I haven't looked into how one would go about that. I am guessing that you have found a solution by now anyways 🙂

I would guess the reason for you not having seen any literate configs split into multiple files, is that org-mode handles large files really well.
